/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoShopRouteImport } from './routes/demo-shop'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinSlugRouteImport } from './routes/join/$slug'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedConsumerRouteRouteImport } from './routes/_authenticated/consumer/route'
import { Route as AuthenticatedBusinessRouteRouteImport } from './routes/_authenticated/business/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedConsumerSettingsRouteImport } from './routes/_authenticated/consumer/settings'
import { Route as AuthenticatedConsumerOnboardingRouteImport } from './routes/_authenticated/consumer/onboarding'
import { Route as AuthenticatedConsumerNotificationsRouteImport } from './routes/_authenticated/consumer/notifications'
import { Route as AuthenticatedConsumerHomeRouteImport } from './routes/_authenticated/consumer/home'
import { Route as AuthenticatedConsumerFindRewardsRouteImport } from './routes/_authenticated/consumer/find-rewards'
import { Route as AuthenticatedConsumerCardsRouteImport } from './routes/_authenticated/consumer/cards'
import { Route as AuthenticatedBusinessSettingsRouteImport } from './routes/_authenticated/business/settings'
import { Route as AuthenticatedBusinessRegisterRouteImport } from './routes/_authenticated/business/register'
import { Route as AuthenticatedBusinessRedemptionsRouteImport } from './routes/_authenticated/business/redemptions'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business/dashboard'
import { Route as AuthenticatedBusinessAnalyticsRouteImport } from './routes/_authenticated/business/analytics'
import { Route as AuthenticatedConsumerRewardsIndexRouteImport } from './routes/_authenticated/consumer/rewards/index'
import { Route as AuthenticatedBusinessProgramsIndexRouteImport } from './routes/_authenticated/business/programs/index'
import { Route as AuthenticatedBusinessProgramsCreateRouteImport } from './routes/_authenticated/business/programs/create'
import { Route as AuthenticatedConsumerRewardsClaimIdClaimRouteImport } from './routes/_authenticated/consumer/rewards/$claimId/claim'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoShopRoute = DemoShopRouteImport.update({
  id: '/demo-shop',
  path: '/demo-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsumerRouteRoute =
  AuthenticatedConsumerRouteRouteImport.update({
    id: '/consumer',
    path: '/consumer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessRouteRoute =
  AuthenticatedBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsumerSettingsRoute =
  AuthenticatedConsumerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedConsumerOnboardingRoute =
  AuthenticatedConsumerOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedConsumerNotificationsRoute =
  AuthenticatedConsumerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedConsumerHomeRoute =
  AuthenticatedConsumerHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedConsumerFindRewardsRoute =
  AuthenticatedConsumerFindRewardsRouteImport.update({
    id: '/find-rewards',
    path: '/find-rewards',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedConsumerCardsRoute =
  AuthenticatedConsumerCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedBusinessSettingsRoute =
  AuthenticatedBusinessSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessRegisterRoute =
  AuthenticatedBusinessRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessRedemptionsRoute =
  AuthenticatedBusinessRedemptionsRouteImport.update({
    id: '/redemptions',
    path: '/redemptions',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessAnalyticsRoute =
  AuthenticatedBusinessAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedConsumerRewardsIndexRoute =
  AuthenticatedConsumerRewardsIndexRouteImport.update({
    id: '/rewards/',
    path: '/rewards/',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)
const AuthenticatedBusinessProgramsIndexRoute =
  AuthenticatedBusinessProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessProgramsCreateRoute =
  AuthenticatedBusinessProgramsCreateRouteImport.update({
    id: '/programs/create',
    path: '/programs/create',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedConsumerRewardsClaimIdClaimRoute =
  AuthenticatedConsumerRewardsClaimIdClaimRouteImport.update({
    id: '/rewards/$claimId/claim',
    path: '/rewards/$claimId/claim',
    getParentRoute: () => AuthenticatedConsumerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/demo-shop': typeof DemoShopRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/consumer': typeof AuthenticatedConsumerRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/join/$slug': typeof JoinSlugRoute
  '/business/analytics': typeof AuthenticatedBusinessAnalyticsRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/redemptions': typeof AuthenticatedBusinessRedemptionsRoute
  '/business/register': typeof AuthenticatedBusinessRegisterRoute
  '/business/settings': typeof AuthenticatedBusinessSettingsRoute
  '/consumer/cards': typeof AuthenticatedConsumerCardsRoute
  '/consumer/find-rewards': typeof AuthenticatedConsumerFindRewardsRoute
  '/consumer/home': typeof AuthenticatedConsumerHomeRoute
  '/consumer/notifications': typeof AuthenticatedConsumerNotificationsRoute
  '/consumer/onboarding': typeof AuthenticatedConsumerOnboardingRoute
  '/consumer/settings': typeof AuthenticatedConsumerSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/business/programs/create': typeof AuthenticatedBusinessProgramsCreateRoute
  '/business/programs': typeof AuthenticatedBusinessProgramsIndexRoute
  '/consumer/rewards': typeof AuthenticatedConsumerRewardsIndexRoute
  '/consumer/rewards/$claimId/claim': typeof AuthenticatedConsumerRewardsClaimIdClaimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/demo-shop': typeof DemoShopRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/consumer': typeof AuthenticatedConsumerRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/join/$slug': typeof JoinSlugRoute
  '/business/analytics': typeof AuthenticatedBusinessAnalyticsRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/redemptions': typeof AuthenticatedBusinessRedemptionsRoute
  '/business/register': typeof AuthenticatedBusinessRegisterRoute
  '/business/settings': typeof AuthenticatedBusinessSettingsRoute
  '/consumer/cards': typeof AuthenticatedConsumerCardsRoute
  '/consumer/find-rewards': typeof AuthenticatedConsumerFindRewardsRoute
  '/consumer/home': typeof AuthenticatedConsumerHomeRoute
  '/consumer/notifications': typeof AuthenticatedConsumerNotificationsRoute
  '/consumer/onboarding': typeof AuthenticatedConsumerOnboardingRoute
  '/consumer/settings': typeof AuthenticatedConsumerSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/business/programs/create': typeof AuthenticatedBusinessProgramsCreateRoute
  '/business/programs': typeof AuthenticatedBusinessProgramsIndexRoute
  '/consumer/rewards': typeof AuthenticatedConsumerRewardsIndexRoute
  '/consumer/rewards/$claimId/claim': typeof AuthenticatedConsumerRewardsClaimIdClaimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/demo-shop': typeof DemoShopRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/_authenticated/consumer': typeof AuthenticatedConsumerRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/join/$slug': typeof JoinSlugRoute
  '/_authenticated/business/analytics': typeof AuthenticatedBusinessAnalyticsRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/business/redemptions': typeof AuthenticatedBusinessRedemptionsRoute
  '/_authenticated/business/register': typeof AuthenticatedBusinessRegisterRoute
  '/_authenticated/business/settings': typeof AuthenticatedBusinessSettingsRoute
  '/_authenticated/consumer/cards': typeof AuthenticatedConsumerCardsRoute
  '/_authenticated/consumer/find-rewards': typeof AuthenticatedConsumerFindRewardsRoute
  '/_authenticated/consumer/home': typeof AuthenticatedConsumerHomeRoute
  '/_authenticated/consumer/notifications': typeof AuthenticatedConsumerNotificationsRoute
  '/_authenticated/consumer/onboarding': typeof AuthenticatedConsumerOnboardingRoute
  '/_authenticated/consumer/settings': typeof AuthenticatedConsumerSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/business/programs/create': typeof AuthenticatedBusinessProgramsCreateRoute
  '/_authenticated/business/programs/': typeof AuthenticatedBusinessProgramsIndexRoute
  '/_authenticated/consumer/rewards/': typeof AuthenticatedConsumerRewardsIndexRoute
  '/_authenticated/consumer/rewards/$claimId/claim': typeof AuthenticatedConsumerRewardsClaimIdClaimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo-shop'
    | '/login'
    | '/signup'
    | '/business'
    | '/consumer'
    | '/account'
    | '/upgrade'
    | '/join/$slug'
    | '/business/analytics'
    | '/business/dashboard'
    | '/business/redemptions'
    | '/business/register'
    | '/business/settings'
    | '/consumer/cards'
    | '/consumer/find-rewards'
    | '/consumer/home'
    | '/consumer/notifications'
    | '/consumer/onboarding'
    | '/consumer/settings'
    | '/api/auth/$'
    | '/business/programs/create'
    | '/business/programs'
    | '/consumer/rewards'
    | '/consumer/rewards/$claimId/claim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo-shop'
    | '/login'
    | '/signup'
    | '/business'
    | '/consumer'
    | '/account'
    | '/upgrade'
    | '/join/$slug'
    | '/business/analytics'
    | '/business/dashboard'
    | '/business/redemptions'
    | '/business/register'
    | '/business/settings'
    | '/consumer/cards'
    | '/consumer/find-rewards'
    | '/consumer/home'
    | '/consumer/notifications'
    | '/consumer/onboarding'
    | '/consumer/settings'
    | '/api/auth/$'
    | '/business/programs/create'
    | '/business/programs'
    | '/consumer/rewards'
    | '/consumer/rewards/$claimId/claim'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/demo-shop'
    | '/login'
    | '/signup'
    | '/_authenticated/business'
    | '/_authenticated/consumer'
    | '/_authenticated/account'
    | '/_authenticated/upgrade'
    | '/join/$slug'
    | '/_authenticated/business/analytics'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/business/redemptions'
    | '/_authenticated/business/register'
    | '/_authenticated/business/settings'
    | '/_authenticated/consumer/cards'
    | '/_authenticated/consumer/find-rewards'
    | '/_authenticated/consumer/home'
    | '/_authenticated/consumer/notifications'
    | '/_authenticated/consumer/onboarding'
    | '/_authenticated/consumer/settings'
    | '/api/auth/$'
    | '/_authenticated/business/programs/create'
    | '/_authenticated/business/programs/'
    | '/_authenticated/consumer/rewards/'
    | '/_authenticated/consumer/rewards/$claimId/claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  DemoShopRoute: typeof DemoShopRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JoinSlugRoute: typeof JoinSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-shop': {
      id: '/demo-shop'
      path: '/demo-shop'
      fullPath: '/demo-shop'
      preLoaderRoute: typeof DemoShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consumer': {
      id: '/_authenticated/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof AuthenticatedConsumerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consumer/settings': {
      id: '/_authenticated/consumer/settings'
      path: '/settings'
      fullPath: '/consumer/settings'
      preLoaderRoute: typeof AuthenticatedConsumerSettingsRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/consumer/onboarding': {
      id: '/_authenticated/consumer/onboarding'
      path: '/onboarding'
      fullPath: '/consumer/onboarding'
      preLoaderRoute: typeof AuthenticatedConsumerOnboardingRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/consumer/notifications': {
      id: '/_authenticated/consumer/notifications'
      path: '/notifications'
      fullPath: '/consumer/notifications'
      preLoaderRoute: typeof AuthenticatedConsumerNotificationsRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/consumer/home': {
      id: '/_authenticated/consumer/home'
      path: '/home'
      fullPath: '/consumer/home'
      preLoaderRoute: typeof AuthenticatedConsumerHomeRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/consumer/find-rewards': {
      id: '/_authenticated/consumer/find-rewards'
      path: '/find-rewards'
      fullPath: '/consumer/find-rewards'
      preLoaderRoute: typeof AuthenticatedConsumerFindRewardsRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/consumer/cards': {
      id: '/_authenticated/consumer/cards'
      path: '/cards'
      fullPath: '/consumer/cards'
      preLoaderRoute: typeof AuthenticatedConsumerCardsRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/business/settings': {
      id: '/_authenticated/business/settings'
      path: '/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof AuthenticatedBusinessSettingsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/register': {
      id: '/_authenticated/business/register'
      path: '/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof AuthenticatedBusinessRegisterRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/redemptions': {
      id: '/_authenticated/business/redemptions'
      path: '/redemptions'
      fullPath: '/business/redemptions'
      preLoaderRoute: typeof AuthenticatedBusinessRedemptionsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/analytics': {
      id: '/_authenticated/business/analytics'
      path: '/analytics'
      fullPath: '/business/analytics'
      preLoaderRoute: typeof AuthenticatedBusinessAnalyticsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/consumer/rewards/': {
      id: '/_authenticated/consumer/rewards/'
      path: '/rewards'
      fullPath: '/consumer/rewards'
      preLoaderRoute: typeof AuthenticatedConsumerRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
    '/_authenticated/business/programs/': {
      id: '/_authenticated/business/programs/'
      path: '/programs'
      fullPath: '/business/programs'
      preLoaderRoute: typeof AuthenticatedBusinessProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/programs/create': {
      id: '/_authenticated/business/programs/create'
      path: '/programs/create'
      fullPath: '/business/programs/create'
      preLoaderRoute: typeof AuthenticatedBusinessProgramsCreateRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/consumer/rewards/$claimId/claim': {
      id: '/_authenticated/consumer/rewards/$claimId/claim'
      path: '/rewards/$claimId/claim'
      fullPath: '/consumer/rewards/$claimId/claim'
      preLoaderRoute: typeof AuthenticatedConsumerRewardsClaimIdClaimRouteImport
      parentRoute: typeof AuthenticatedConsumerRouteRoute
    }
  }
}

interface AuthenticatedBusinessRouteRouteChildren {
  AuthenticatedBusinessAnalyticsRoute: typeof AuthenticatedBusinessAnalyticsRoute
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedBusinessRedemptionsRoute: typeof AuthenticatedBusinessRedemptionsRoute
  AuthenticatedBusinessRegisterRoute: typeof AuthenticatedBusinessRegisterRoute
  AuthenticatedBusinessSettingsRoute: typeof AuthenticatedBusinessSettingsRoute
  AuthenticatedBusinessProgramsCreateRoute: typeof AuthenticatedBusinessProgramsCreateRoute
  AuthenticatedBusinessProgramsIndexRoute: typeof AuthenticatedBusinessProgramsIndexRoute
}

const AuthenticatedBusinessRouteRouteChildren: AuthenticatedBusinessRouteRouteChildren =
  {
    AuthenticatedBusinessAnalyticsRoute: AuthenticatedBusinessAnalyticsRoute,
    AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
    AuthenticatedBusinessRedemptionsRoute:
      AuthenticatedBusinessRedemptionsRoute,
    AuthenticatedBusinessRegisterRoute: AuthenticatedBusinessRegisterRoute,
    AuthenticatedBusinessSettingsRoute: AuthenticatedBusinessSettingsRoute,
    AuthenticatedBusinessProgramsCreateRoute:
      AuthenticatedBusinessProgramsCreateRoute,
    AuthenticatedBusinessProgramsIndexRoute:
      AuthenticatedBusinessProgramsIndexRoute,
  }

const AuthenticatedBusinessRouteRouteWithChildren =
  AuthenticatedBusinessRouteRoute._addFileChildren(
    AuthenticatedBusinessRouteRouteChildren,
  )

interface AuthenticatedConsumerRouteRouteChildren {
  AuthenticatedConsumerCardsRoute: typeof AuthenticatedConsumerCardsRoute
  AuthenticatedConsumerFindRewardsRoute: typeof AuthenticatedConsumerFindRewardsRoute
  AuthenticatedConsumerHomeRoute: typeof AuthenticatedConsumerHomeRoute
  AuthenticatedConsumerNotificationsRoute: typeof AuthenticatedConsumerNotificationsRoute
  AuthenticatedConsumerOnboardingRoute: typeof AuthenticatedConsumerOnboardingRoute
  AuthenticatedConsumerSettingsRoute: typeof AuthenticatedConsumerSettingsRoute
  AuthenticatedConsumerRewardsIndexRoute: typeof AuthenticatedConsumerRewardsIndexRoute
  AuthenticatedConsumerRewardsClaimIdClaimRoute: typeof AuthenticatedConsumerRewardsClaimIdClaimRoute
}

const AuthenticatedConsumerRouteRouteChildren: AuthenticatedConsumerRouteRouteChildren =
  {
    AuthenticatedConsumerCardsRoute: AuthenticatedConsumerCardsRoute,
    AuthenticatedConsumerFindRewardsRoute:
      AuthenticatedConsumerFindRewardsRoute,
    AuthenticatedConsumerHomeRoute: AuthenticatedConsumerHomeRoute,
    AuthenticatedConsumerNotificationsRoute:
      AuthenticatedConsumerNotificationsRoute,
    AuthenticatedConsumerOnboardingRoute: AuthenticatedConsumerOnboardingRoute,
    AuthenticatedConsumerSettingsRoute: AuthenticatedConsumerSettingsRoute,
    AuthenticatedConsumerRewardsIndexRoute:
      AuthenticatedConsumerRewardsIndexRoute,
    AuthenticatedConsumerRewardsClaimIdClaimRoute:
      AuthenticatedConsumerRewardsClaimIdClaimRoute,
  }

const AuthenticatedConsumerRouteRouteWithChildren =
  AuthenticatedConsumerRouteRoute._addFileChildren(
    AuthenticatedConsumerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBusinessRouteRoute: typeof AuthenticatedBusinessRouteRouteWithChildren
  AuthenticatedConsumerRouteRoute: typeof AuthenticatedConsumerRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBusinessRouteRoute: AuthenticatedBusinessRouteRouteWithChildren,
  AuthenticatedConsumerRouteRoute: AuthenticatedConsumerRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  DemoShopRoute: DemoShopRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JoinSlugRoute: JoinSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
